/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicauca.gestorvisitasmuseo.presentation;

import com.unicauca.gestorvisitasmuseo.dao.VisitaJpaController;
import com.unicauca.gestorvisitasmuseo.entities.Visita;
import com.unicauca.gestorvisitasmuseo.logica.HandlerTable;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian V
 */
public class Principal extends javax.swing.JFrame {

    EntityManagerFactory factory;
    VisitaJpaController jpa;
    HandlerTable controladorTabla;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        controladorTabla = new HandlerTable();
        factory = Persistence.createEntityManagerFactory("GestorVisitasMuseoPU");
        jpa = new VisitaJpaController(factory);
        txtObservaciones.setEnabled(false);
        txtFecha.setEnabled(false);
        txtHora.setEnabled(false);

        verificarConexion();

        /*Para centrar la ventana*/
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
//obtenemos el tamaño de la ventana
        Dimension ventana = this.getSize();
//para centrar la ventana lo hacemos con el siguiente calculo
        this.setLocation((pantalla.width - ventana.width) / 2, 0);
//y para finalizar la hacemos visible
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        lblImagenLogo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        spinNumeroPersonas = new javax.swing.JSpinner();
        cbBoxGrupoSocial = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        checkComentarios = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        btnGuardarVisita = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConsultas = new javax.swing.JTable();
        btnBuscarObservacion = new javax.swing.JButton();
        txtBuscarObservacion = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jDateFechaIni = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jDateFechafin = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbxOpcionesFechas = new javax.swing.JComboBox<>();
        btnConsultaFechas = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblImagenLogo1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemConsultarTodo = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestor Matriz Control de Ingreso de Visitantes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Casa Museo Guillermo León Valencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/museo.png"))); // NOI18N
        jPanel2.add(lblImagenLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, -1, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Casa Museo Guillermo León Valencia");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 28, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 10, 70));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("Teléfono: +57 (2) 824 1555 ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("Dirección: Calle 5 # 9- 82");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setText("Correo electrónico: museoguillermoleonvalencia@mincultura.gov.co");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Número de visitantes:");

        spinNumeroPersonas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        cbBoxGrupoSocial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niño", "Joven", "Adulto", "Adulto Mayor" }));

        jLabel1.setText("GrupoSocial:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane2.setViewportView(txtObservaciones);

        checkComentarios.setText("Comentarios u observaciones:");
        checkComentarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkComentariosMouseClicked(evt);
            }
        });

        jLabel3.setText("Fecha:");

        txtFecha.setEditable(false);
        txtFecha.setText(" ");

        jLabel4.setText("Hora:");

        txtHora.setEditable(false);
        txtHora.setText(" ");

        btnGuardarVisita.setText("Guardar visita");
        btnGuardarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVisitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(checkComentarios)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(spinNumeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBoxGrupoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinNumeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbBoxGrupoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkComentarios)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnGuardarVisita)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Registro de ingreso de visitantes", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblConsultas.setAutoCreateRowSorter(true);
        tblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblConsultas);

        btnBuscarObservacion.setText("Buscar");
        btnBuscarObservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarObservacionActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel5.setText("Consultar por observaciones:");

        jLabel12.setText("y");

        jLabel13.setText("Consultar visitas entre:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setText("(Fecha inicial)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setText("(Fecha final)");

        cbxOpcionesFechas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ver detalle", "Conteo" }));

        btnConsultaFechas.setText("Aceptar");
        btnConsultaFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaFechasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addComponent(txtBuscarObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(btnBuscarObservacion))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jDateFechafin, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxOpcionesFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnConsultaFechas))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel15))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(152, 180, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateFechafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbxOpcionesFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnConsultaFechas)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtBuscarObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarObservacion))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnLimpiar))
        );

        jTabbedPane1.addTab("Consultas y Reportes", jPanel3);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Matriz Control de Ingreso de Visitantes");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Escudo.png"))); // NOI18N

        lblImagenLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logomuseo.png"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(0, 87, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Archivo");

        MenuItemConsultarTodo.setText("Consultar todos los registros");
        MenuItemConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemConsultarTodoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemConsultarTodo);

        jMenuItem2.setText("Cerrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de...");

        jMenuItem1.setText("Versión Sistema Gestor Matriz Control de Ingreso de Visitantes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem3.setText("Contacto Proveedor - Desarrollador");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImagenLogo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblImagenLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("sdfgsd");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkComentariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkComentariosMouseClicked
        if (checkComentarios.isSelected()) {
            txtObservaciones.setEnabled(true);
        } else {
            txtObservaciones.setEnabled(false);
        }
    }//GEN-LAST:event_checkComentariosMouseClicked

    private void btnGuardarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVisitaActionPerformed
        logicaGuardar();
    }//GEN-LAST:event_btnGuardarVisitaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarObservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarObservacionActionPerformed
        logicaConsultarObservacion();
    }//GEN-LAST:event_btnBuscarObservacionActionPerformed

    private void btnConsultaFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaFechasActionPerformed
        logicaConsultasFecha();
    }//GEN-LAST:event_btnConsultaFechasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String mj = "\tSistema Gestor de Matriz Control de Ingreso de Visitantes\n"
                + "\tVersión 1.1\n"
                + "Casa Museo Guillermo León Valencia";
        JOptionPane.showMessageDialog(this, mj, "Versión de sistema", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String mj = "Desarrollado por:\n"
                + "Juan Sebastián Vásquez (jsvasquez@unicauca.edu.co)\n"
                + "Cel: 312 203 7795\n"
                + "Gestor Matriz Control de Ingreso de Visitantes";
        JOptionPane.showMessageDialog(this, mj, "Datos de contacto", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MenuItemConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemConsultarTodoActionPerformed
        logicaConsultaTotal();
    }//GEN-LAST:event_MenuItemConsultarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemConsultarTodo;
    private javax.swing.JButton btnBuscarObservacion;
    private javax.swing.JButton btnConsultaFechas;
    private javax.swing.JButton btnGuardarVisita;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbBoxGrupoSocial;
    private javax.swing.JComboBox<String> cbxOpcionesFechas;
    private javax.swing.JCheckBox checkComentarios;
    private com.toedter.calendar.JDateChooser jDateFechaIni;
    private com.toedter.calendar.JDateChooser jDateFechafin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblImagenLogo;
    private javax.swing.JLabel lblImagenLogo1;
    private javax.swing.JSpinner spinNumeroPersonas;
    private javax.swing.JTable tblConsultas;
    private javax.swing.JTextField txtBuscarObservacion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables

    private void logicaGuardar() {
        Date fechaActual = new Date();

        //Formateando la fecha:
//        DateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
//        DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
//        System.out.println("Son las: " + formatoHora.format(fechaActual) + " de fecha: " + formatoFecha.format(fechaActual));
        //Fecha actual desglosada:
        Calendar fecha = Calendar.getInstance();
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH) + 1;
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        int segundo = fecha.get(Calendar.SECOND);

//        System.out.println("Fecha Actual: " + dia + "/" + (mes) + "/" + año);
//        System.out.printf("Hora Actual: %02d:%02d:%02d %n", hora, minuto, segundo);
//        System.out.println("-------------Fecha desglosada----------------");
//        System.out.println("El año es: " + año);
//        System.out.println("El mes es: " + mes);
//        System.out.println("El día es: " + dia);
//        System.out.printf("La hora es: %02d %n", hora);
//        System.out.printf("El minuto es: %02d %n", minuto);
//        System.out.printf("El segundo es: %02d %n", segundo);
        //seteando la interfaz
        txtFecha.setText(año + "-" + mes + "-" + dia);
        txtHora.setText(hora + ":" + minuto + ":" + segundo);

        //creando la nueva visita que se guardará
        Visita visitaNueva = new Visita();

        visitaNueva.setId((long) 1);
        visitaNueva.setFecha(fechaActual);
        visitaNueva.setHora(fechaActual);
        visitaNueva.setTipovisitante(cbBoxGrupoSocial.getSelectedItem().toString());
        visitaNueva.setNumeropersonas((int) spinNumeroPersonas.getValue());
        if (checkComentarios.isSelected()) {
            visitaNueva.setObservaciones(txtObservaciones.getText());
        }
        try {

            System.out.println("se va a insertar: " + visitaNueva);
            jpa.create(visitaNueva);
            JOptionPane.showMessageDialog(this, "Resumen:\n" + visitaNueva.toString(), "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);

//            System.out.println("Visitas registradas hasta el momento:");
//            List<Visita> visitas = jpa.findVisitaEntities();
//            for (int i = 0; i < visitas.size(); i++) {
//                System.out.println(visitas.get(i));
//            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Verifique que la base de datos esté iniciada.\n"
                    + "\nSi persiste, contacte al proveedor.\n"
                    + "Detalles de error: \n" + e.getMessage(),
                    "Ha ocurrido un error", JOptionPane.ERROR_MESSAGE);

            JOptionPane.showMessageDialog(this, "\tRecuerde registrar nuevamente esta visita.", "Visita no registrada", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void logicaConsultaTotal() {
        try {
            if (!controladorTabla.ejecutarConsulta(tblConsultas, 1, null)) {
                JOptionPane.showMessageDialog(this, "No se han encontrado registros aún en el sistema.", "No hay registros", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            String mj = "Detalle de error:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mj, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void logicaConsultarObservacion() {
        try {
            String criterio = txtBuscarObservacion.getText().toLowerCase().trim();
            if (!criterio.equals("")) {
                if (!controladorTabla.ejecutarConsulta(tblConsultas, 2, criterio)) {
                    JOptionPane.showMessageDialog(this, "No se han encontrado registros relacionados.", "", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El campo de búsqueda no puede estar vacío.\nPor favor intente nuevamente.", "", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            String mj = "Error: Contacte al adeministrador.";
            JOptionPane.showMessageDialog(this, mj, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void limpiarTabla() {
        tblConsultas.setModel(new DefaultTableModel());
    }

    private void logicaConsultarFechas() {
        Date fInicio = jDateFechaIni.getDate();
        Date fFin = jDateFechafin.getDate();
        if (fInicio == null) {
            JOptionPane.showMessageDialog(this, "Las fecha inicial es requerida. \nNo puede estar vacía o incompleta.", "Intente nuevamente", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (fFin == null) {
                fFin = new Date();
            }

            if (!controladorTabla.consultarFechas(tblConsultas, fInicio, fFin)) {
                JOptionPane.showMessageDialog(this, "No se han encontrado registros entre "+normalizarFecha(fInicio)+" y "+normalizarFecha(fFin)+".", "", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }

    private void logicaContarVisitasFechas() {
        Date fInicio = jDateFechaIni.getDate();
        Date fFin = jDateFechafin.getDate();
        if (fInicio == null) {
            JOptionPane.showMessageDialog(this, "Las fecha inicial es requerida. \nNo puede estar vacía o incompleta.", "Intente nuevamente", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (fFin == null) {
                fFin = new Date();
            }
            List<Integer> conteos = controladorTabla.contarVisitasFechas(fInicio, fFin);

            JOptionPane.showMessageDialog(this, "A continuación se presenta el resumen de visitas entre " + normalizarFecha(fInicio) + " y " + normalizarFecha(fFin) + " clasificadas por tipo de visitante.\n"
                    + "\nNiño: " + conteos.get(0)
                    + "\nJoven: " + conteos.get(1)
                    + "\nAdulto: " + conteos.get(2)
                    + "\nAdulto Mayor: " + conteos.get(3), "Resumen de visitas", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void logicaConsultasFecha() {
        try {
            System.out.println(cbxOpcionesFechas.getSelectedIndex());
            if (cbxOpcionesFechas.getSelectedIndex() == 0) {
                logicaConsultarFechas();
            } else if (cbxOpcionesFechas.getSelectedIndex() == 1) {
                logicaContarVisitasFechas();
            }
        } catch (Exception e) {
            String mj = "Error: Contacte al adeministrador.";
            JOptionPane.showMessageDialog(this, mj, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void verificarConexion() {

        try {
            controladorTabla.puedeAcceder();
        } catch (Exception e) {
            String mj = "Base de datos no iniciada.\n"
                    + "Recuerda iniciar el servicio de base de datos para utilizar el aplicativo, de lo contrario no funcionará correctamente.\n";
            JOptionPane.showMessageDialog(this, mj, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public String normalizarFecha(Date fechaBruta) {
        Calendar fechaLista = Calendar.getInstance();
        fechaLista.setTime(fechaBruta);
        int d = fechaLista.get(Calendar.DAY_OF_MONTH);
        int m = (fechaLista.get(Calendar.MONTH) + 1);
        String anio = "" + fechaLista.get(Calendar.YEAR);

        String dia = "" + d;
        if (d < 10) {
            dia = "0" + d;
        }
        String mes = "" + m;
        if (m < 10) {
            mes = "0" + m;
        }

        return dia + "/" + mes + "/" + anio;
    }
}
